#!/usr/bin/env python3
"""
Convert .tflite -> C source pair for embedding in the ESP32-S3 firmware.

Usage:
    python tflite_to_c.py model.tflite ../esp32_ble_inference/src/model_data.cc
"""
import argparse
from pathlib import Path

HEADER = """// Auto-generated by tflite_to_c.py.
#ifndef MODEL_DATA_H_
#define MODEL_DATA_H_

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

extern const unsigned char g_model_data[];
extern const unsigned int  g_model_data_len;

#ifdef __cplusplus
}
#endif

#endif  // MODEL_DATA_H_
"""

SOURCE = """// Auto-generated by tflite_to_c.py.
#include "model_data.h"

alignas(8) const unsigned char g_model_data[] = {{
{body}
}};

const unsigned int g_model_data_len = {length}u;
"""


def to_c(data: bytes, width: int = 12) -> str:
    return '\n'.join(
        '  ' + ', '.join(f'0x{b:02x}' for b in data[i:i + width]) + ','
        for i in range(0, len(data), width)
    )


def main():
    p = argparse.ArgumentParser()
    p.add_argument('input', type=Path)
    p.add_argument('output', type=Path)
    args = p.parse_args()

    data = args.input.read_bytes()
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(SOURCE.format(body=to_c(data), length=len(data)))
    args.output.with_suffix('.h').write_text(HEADER)
    print(f'Wrote {args.output} ({len(data)} bytes)')


if __name__ == '__main__':
    main()
